version: '3'
services:
        mysql:
                image: izzytang/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: root
        php-fpm:
                image: izzytang/php-fpm
                volumes:
                        - /tmp/docker/lnmp/html:/var/www/html
        nginx:
                image: izzytang/nginx
                volumes:
                        - /tmp/docker/lnmp/html:/var/www/html
                ports:
                        - 80:80
